### ISSUE TITLE
Program can't recognise my game folder

### ISSUE THREAD

**Issue by Theguysayhi** [mathewv/wolftrans#6]
I'm sure this in an amazing piece of software but whenever I run the command: wolftrans game_dir patch_dir out_dir
It comes up with:
/usr/local/lib/ruby/gems/2.3.0/gems/wolftrans-0.2.0/lib/wolftrans/patch_data.rb:14:in `load_data': could not find game folder 'game_dir' (RuntimeError)

I assume this is because it can't pick up a game folder but I've tried everything to my knowledge to get it to work, including renaming, and putting it in different folders in the directory. Is this an issue or am I doing something wrong?

**Comment by N1nj4R4bb1D** [comment]
Could you provide full command line you are trying to use?

Example:
  wolftrans D:\Games\GameToTranslate D:\Games\GamePatchFiles D:\Games\TranslatedGame

**Comment by Theguysayhi** [comment]
Ah thanks I fixed the problem I was having thanks to your help.

I didn't realise that the command required actual directory names and instead quite literally wrote "wolftrans game_dir patch_dir out_dir" in my command.

Fixed the issue by substituting "game_dir" "patch_dir" "out_dir" for directory names with my folders.

"wolftrans /usr/local/lib/ruby/gems/2.3.0/gems/wolftrans-0.2.0/game /usr/local/lib/ruby/gems/2.3.0/gems/wolftrans-0.2.0/patch /usr/local/lib/ruby/gems/2.3.0/gems/wolftrans-0.2.0/out"

Thanks.
